// src/components/editor/Navbar.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogTrigger,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import upiQR from "/assets/upiQR.png";
import {
  Download,
  ChevronDown,
  Coffee,
  ExternalLink,
  Loader2,
  Heart,
  X,
  CheckCircle,
} from "lucide-react";
import { Github } from "@/components/icons/Github";
import { Bluesky } from "@/components/icons/Bluesky";
import { X as XIcon } from "@/components/icons/X";

import { toast } from "sonner";
import { useMockupStore } from "@/contexts/MockupContext";
import html2canvas from "html2canvas";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

export function Navbar() {
  const [showExportOptions, setShowExportOptions] = useState(false);
  const [exportFormat, setExportFormat] = useState("PNG");
  const [quality, setQuality] = useState([2]);
  const [isExporting, setIsExporting] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const { uploadedImage, imageBorder, fixedMargin, margin } = useMockupStore();

  const isMobile = typeof window !== "undefined" ? window.innerWidth < 768 : false;

  const getQualityLabel = (value) => {
    switch (value) {
      case 1:
        return "Standard (1x)";
      case 2:
        return "High (2x)";
      case 3:
        return "Ultra (3x)";
      default:
        return `${value}x`;
    }
  };

  const exportImage = async (format: string, qualityMultiplier: number) => {
    if (!uploadedImage) return;

    try {
      const mockupElement = document.querySelector("[data-mockup-canvas]") as HTMLDivElement;
      if (!mockupElement) throw new Error("Mockup canvas not found");

      const imgElement = mockupElement.querySelector("img") as HTMLImageElement;
      if (!imgElement) throw new Error("Image element not found");

      // For fixed margin mode: capture the entire canvas (image + background margins)
      const canvas = await html2canvas(mockupElement, {
        scale: qualityMultiplier * 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: null,
        // Capture the entire mockup element without any cropping
      });

      const mimeType = `image/${format.toLowerCase()}`;
      const imageQuality = format === "JPEG" ? 1 : undefined;

      canvas.toBlob(
        (blob) => {
          if (blob) {
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `mockup-${Date.now()}.${format.toLowerCase()}`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
          } else {
            throw new Error("Failed to create blob");
          }
        },
        mimeType,
        imageQuality,
      );
    } catch (error) {
      console.error("Export error:", error);
      throw error;
    }
  };

  const handleSingleExport = async () => {
    if (!uploadedImage) {
      toast.error("Please upload an image first");
      return;
    }

    setIsExporting(true);
    try {
      await exportImage(exportFormat, quality[0]);
      toast.success(`Successfully exported as ${exportFormat}!`, {
        icon: <CheckCircle className="w-4 h-4" />,
      });
    } catch (error) {
      toast.error("Failed to export image. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleAllFormatsExport = async () => {
    if (!uploadedImage) {
      toast.error("Please upload an image first");
      return;
    }

    setIsExporting(true);
    const formats = ["PNG", "JPEG", "WebP"];
    const qualityMultiplier = quality[0];

    try {
      await Promise.all(formats.map((format) => exportImage(format, qualityMultiplier)));

      toast.success(`Successfully exported all formats (${formats.join(", ")})!`, {
        icon: <CheckCircle className="w-4 h-4" />,
      });
    } catch (error) {
      console.error("Export all formats error:", error);
      toast.error("Failed to export some formats. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  const ExportOptionsContent = () => (
    <div
      className={`
        ${isMobile ? "flex flex-col gap-2" : "grid grid-cols-2 gap-6"}
      `}
    >
      <div className={`${!isMobile ? "order-2" : "order-1"}`}>
        <div>
          <h3 className="text-xl font-semibold text-foreground mb-6 flex items-center gap-2">
            <Download className="w-5 h-5 text-primary" />
            Export Settings
          </h3>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium">Format</label>
            </div>
            <ToggleGroup
              type="single"
              value={exportFormat}
              onValueChange={(value) => value && setExportFormat(value)}
              className="flex gap-1 bg-sidebar/80 rounded-full ring-2 ring-secondary p-1"
            >
              {["PNG", "JPEG", "WebP"].map((format) => (
                <ToggleGroupItem
                  key={format}
                  value={format}
                  className={`flex-1 text-sm rounded-full cursor-pointer hover:bg-secondary hover:text-secondary-foreground data-[state=on]:bg-primary/20 data-[state=on]:text-primary`}
                >
                  {format}
                </ToggleGroupItem>
              ))}
            </ToggleGroup>
          </div>

          <div className="space-y-2 mt-6">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium">Quality</label>
            </div>
            <ToggleGroup
              type="single"
              value={String(quality[0])}
              onValueChange={(value) => value && setQuality([parseInt(value)])}
              className="flex gap-1 bg-sidebar/80 rounded-full ring-2 ring-secondary p-1"
            >
              <ToggleGroupItem
                value="1"
                className="flex-1 text-sm rounded-full cursor-pointer hover:bg-secondary hover:text-secondary-foreground data-[state=on]:bg-primary/20 data-[state=on]:text-primary"
              >
                Standard
              </ToggleGroupItem>
              <ToggleGroupItem
                value="2"
                className="flex-1 text-sm rounded-full cursor-pointer hover:bg-secondary hover:text-secondary-foreground data-[state=on]:bg-primary/20 data-[state=on]:text-primary"
              >
                High
              </ToggleGroupItem>
              <ToggleGroupItem
                value="3"
                className="flex-1 text-sm rounded-full cursor-pointer hover:bg-secondary hover:text-secondary-foreground data-[state=on]:bg-primary/20 data-[state=on]:text-primary"
              >
                Ultra
              </ToggleGroupItem>
            </ToggleGroup>
          </div>
        </div>
        <div className="space-y-3 grid grid-cols-2 gap-3 mt-12">
          <Button
            onClick={handleSingleExport}
            className="w-full h-12 font-medium shadow-md"
            variant="secondary"
            disabled={isExporting || !uploadedImage}
          >
            {isExporting ? (
              <>
                <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                Exporting...
              </>
            ) : (
              <>
                <Download className="w-5 h-5 mr-2" />
                Export as {exportFormat}
              </>
            )}
          </Button>
          <Button
            onClick={handleAllFormatsExport}
            variant="outline"
            className="w-full h-12 font-medium"
            disabled={isExporting || !uploadedImage}
          >
            {isExporting ? (
              <>
                <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                Exporting All...
              </>
            ) : (
              <>
                <Download className="w-5 h-5 mr-2" />
                Export All Formats
              </>
            )}
          </Button>
        </div>

        <Button variant="link" className="w-full">
          <a
            href="https://github.com/jellydeck/moocup"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex gap-2 w-full grid-cols-2"
          >
            <Github className="size-5" />
            Hey, You can also help us out at here
          </a>
        </Button>
      </div>

      <Card
        className={`rounded-xl border-2 border-dashed border-primary/20 ${!isMobile ? "order-1" : "order-2"} group`}
      >
        <CardHeader className="pb-4">
          <div className="flex items-center gap-2">
            <Heart className="w-5 h-5 text-primary fill-primary/20 group-hover:fill-primary/50 transition-colors group-hover:animate-pulse group-hover:scale-110" />
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <p className="text-sm text-foreground leading-relaxed">
              Hi, I'm
              <a
                href="https://jaydip.me"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 mx-1 text-primary underline hover:no-underline"
              >
                Jaydip
                <ExternalLink className="w-3 h-3" />
              </a>
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              moocup is a simple offline tool.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              focus on your craft, we'll take care of rest.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              you can show your support by sponsoring my work!
            </p>
          </div>
          <div className="space-y-3">
            <Button asChild className="w-full h-12 hover:primary/10 shadow-md">
              <a
                href="https://ko-fi.com/jaydipsanghani"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center"
              >
                <Coffee className="w-5 h-5" />
                <span className="font-medium">Buy a coffee</span>
              </a>
            </Button>
            <Dialog>
              <DialogTrigger asChild>
                <Button
                  variant="outline"
                  className="w-full h-12 border-primary/30 hover:bg-primary/5 hover:border-primary/50 inline-flex items-center"
                >
                  <span className="font-medium">UPI (India)</span>
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-xs">
                <DialogHeader>
                  <DialogTitle className="text-center">Thanks for contribution!</DialogTitle>
                </DialogHeader>
                <div className="flex flex-col items-center gap-4 py-4">
                  <div className="w-48 h-48 bg-muted rounded-xl flex items-center justify-center border-2 border-dashed border-muted-foreground/20">
                    <img
                      src={upiQR}
                      className="size-full"
                      fetchPriority="auto"
                      alt="QR code for making payment in Indian Rupees"
                    />
                  </div>
                  <p className="text-sm text-muted-foreground text-center">Scan with any UPI app</p>
                </div>
              </DialogContent>
            </Dialog>
          </div>
          <div className="space-y-2">
            <h4 className="text-sm font-medium text-muted-foreground">
              Say Hi!
              <span className="ml-2 text-sm text-muted-foreground leading-relaxed">
                I'm always up for quick chat :)
              </span>
            </h4>
            <div className="flex gap-2">
              <Button
                variant="secondary"
                size="sm"
                asChild
                className="flex-1 border-primary/30 hover:border-primary/50"
              >
                <a
                  href="https://bsky.app/profile/jellydeck.bsky.social"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2"
                >
                  <Bluesky className="size-4" />
                  <span>Bluesky</span>
                </a>
              </Button>
              <Button
                variant="secondary"
                size="sm"
                asChild
                className="flex-1 border-primary/30 hover:border-primary/50"
              >
                <a
                  href="https://x.com/JellyDeck"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2"
                >
                  <XIcon className="size-4" />
                  <span>Twitter</span>
                </a>
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );

  return (
    <div className="sticky top-0 z-50 bg-background/80 backdrop-blur-lg border-b">
      <div className="flex items-center justify-between px-4 h-16 lg:mx-40">
        <div className="flex items-center gap-4">
          <div className="flex items-center">
            <h1 className="text-xl font-bold text-primary">Moo</h1>
            <a
              href="https://ko-fi.com/jaydipsanghani"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center"
            >
              <Coffee className="w-6 h-6 text-primary hover:text-primary/80 hover:rotate-12 transition-transform cursor-pointer" />
            </a>
          </div>
          {!isMobile && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <span>crafted by</span>
              <Button variant="link" className="h-auto p-0 text-primary" asChild>
                <a
                  href="https://jaydip.me"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1 underline hover:no-underline!"
                >
                  Jaydip
                </a>
              </Button>
            </div>
          )}
        </div>
        <div className="flex items-center gap-2">
          <a href="https://github.com/jellydeck/moocup" target="_blank" rel="noopener noreferrer">
            <Button variant="outline" className="gap-2 mr-2">
              <Github className="size-5" />
              Send us a star!
            </Button>
          </a>
          {isMobile ? (
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
              <DialogTrigger asChild>
                <Button size="icon" disabled={!uploadedImage} className="h-10 w-10">
                  <Download className="w-5 h-5" />
                </Button>
              </DialogTrigger>
              <DialogContent className="w-[95vw] max-w-md h-[90vh] max-h-[90vh] flex flex-col p-0 [&>button:first-of-type]:hidden">
                <div className="flex items-center justify-between p-4 border-b shrink-0">
                  <DialogTitle className="text-lg font-semibold">Export & Support</DialogTitle>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setIsDialogOpen(false)}
                    className="h-8 w-8"
                  >
                    <X className="w-4 h-4" />
                  </Button>
                </div>
                <div className="flex-1 overflow-y-auto">
                  <div className="px-4 pb-4">
                    <ExportOptionsContent />
                  </div>
                </div>
              </DialogContent>
            </Dialog>
          ) : (
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" disabled={!uploadedImage} className="gap-2 group">
                  <Download className="w-4 h-4" />
                  Export
                  <ChevronDown className="size-4 transition-transform group-data-[state=open]:rotate-180" />
                </Button>
              </PopoverTrigger>

              <PopoverContent
                align="end"
                side="bottom"
                className="w-[900px] p-0.5 border rounded-2xl mt-1.5"
              >
                <Card className="shadow-none border-0">
                  <CardContent className="p-6">
                    <ExportOptionsContent />
                  </CardContent>
                </Card>
              </PopoverContent>
            </Popover>
          )}
        </div>
      </div>
    </div>
  );
}

// src/lib/editor/Navbar.svelte
<script lang="ts">
	import { Dialog, Popover, ToggleGroup } from 'bits-ui';
	import DownloadSimpleIcon from 'phosphor-svelte/lib/DownloadSimpleIcon';
	import CaretDownIcon from 'phosphor-svelte/lib/CaretDownIcon';
	import CoffeeIcon from 'phosphor-svelte/lib/CoffeeIcon';
	import ArrowSquareOutIcon from 'phosphor-svelte/lib/ArrowSquareOutIcon';
	import SpinnerGapIcon from 'phosphor-svelte/lib/SpinnerGapIcon';
	import HeartIcon from 'phosphor-svelte/lib/HeartIcon';
	import XIcon from 'phosphor-svelte/lib/XIcon';
	import GithubLogoIcon from 'phosphor-svelte/lib/GithubLogoIcon';
	import XLogoIcon from 'phosphor-svelte/lib/XLogoIcon';

	import { toast } from 'svelte-sonner';
	import { mockupStore } from '$lib/contexts/store.svelte';
	import html2canvas from 'html2canvas';
	import upiQR from '$lib/assets/upiQR.png';
	import Button from '$lib/components/Button.svelte';

	let exportFormat = $state('PNG');
	let quality = $state('2');
	let isExporting = $state(false);
	let isDialogOpen = $state(false);
	let isUpiDialogOpen = $state(false);

	const { uploadedImage } = $derived(mockupStore);

	const isMobile = typeof window !== 'undefined' ? window.innerWidth < 768 : false;

	async function exportImage(format: string, qualityMultiplier: number) {
		if (!uploadedImage) return;

		const mockupElement = document.querySelector('[data-mockup-canvas]') as HTMLDivElement;
		if (!mockupElement) throw new Error('Mockup canvas not found');

		const imgElement = mockupElement.querySelector('img') as HTMLImageElement;
		if (!imgElement) throw new Error('Image element not found');

		const canvas = await html2canvas(mockupElement, {
			scale: qualityMultiplier * 2,
			useCORS: true,
			allowTaint: true,
			backgroundColor: null
		});

		const mimeType = `image/${format.toLowerCase()}`;
		const imageQuality = format === 'JPEG' ? 1 : undefined;

		canvas.toBlob(
			(blob) => {
				if (!blob) throw new Error('Failed to create blob');
				const url = URL.createObjectURL(blob);
				const a = document.createElement('a');
				a.href = url;
				a.download = `mockup-${Date.now()}.${format.toLowerCase()}`;
				document.body.appendChild(a);
				a.click();
				document.body.removeChild(a);
				URL.revokeObjectURL(url);
			},
			mimeType,
			imageQuality
		);
	}

	async function handleSingleExport() {
		if (!uploadedImage) {
			toast.error('Please upload an image first');
			return;
		}
		isExporting = true;
		try {
			await exportImage(exportFormat, parseInt(quality));
			toast.success(`Successfully exported as ${exportFormat}!`);
		} catch {
			toast.error('Failed to export image. Please try again.');
		} finally {
			isExporting = false;
		}
	}

	// async function handleAllFormatsExport() {
	// 	if (!uploadedImage) {
	// 		toast.error('Please upload an image first');
	// 		return;
	// 	}
	// 	isExporting = true;
	// 	const formats = ['PNG', 'JPEG', 'WebP'];
	// 	try {
	// 		await Promise.all(formats.map((f) => exportImage(f, parseInt(quality))));
	// 		toast.success(`Successfully exported all formats (${formats.join(', ')})!`);
	// 	} catch {
	// 		toast.error('Failed to export some formats. Please try again.');
	// 	} finally {
	// 		isExporting = false;
	// 	}
	// }
</script>

<!-- ─── Export Panel Snippet ──────────────────────────────── -->
{#snippet exportOptions()}
	<div class={isMobile ? 'flex flex-col gap-2' : 'grid grid-cols-2 gap-6'}>
		<!-- Controls col -->
		<div class={!isMobile ? 'order-2' : 'order-1'}>
			<h3 class="text-foreground mb-6 flex items-center gap-2 text-xl font-semibold">
				<DownloadSimpleIcon size={20} class="text-primary" />
				Export Settings
			</h3>

			<!-- Format -->
			<div class="space-y-2">
				<label class="text-sm font-medium">Format</label>
				<ToggleGroup.Root
					type="single"
					bind:value={exportFormat}
					class="bg-sidebar/80 ring-secondary flex gap-1 rounded-full p-1 ring-2"
				>
					{#each ['PNG', 'JPEG', 'WebP'] as fmt}
						<ToggleGroup.Item
							value={fmt}
							class="hover:bg-secondary hover:text-secondary-foreground data-[state=on]:bg-primary/20 data-[state=on]:text-primary flex-1 cursor-pointer rounded-full px-3 py-1.5 text-sm transition-colors"
						>
							{fmt}
						</ToggleGroup.Item>
					{/each}
				</ToggleGroup.Root>
			</div>

			<!-- Quality -->
			<div class="mt-6 space-y-2">
				<label class="text-sm font-medium">Quality</label>
				<ToggleGroup.Root
					type="single"
					bind:value={quality}
					class="bg-sidebar/80 ring-secondary flex gap-1 rounded-full p-1 ring-2"
				>
					{#each [['1', 'Standard'], ['2', 'High'], ['3', 'Ultra']] as [val, label]}
						<ToggleGroup.Item
							value={val}
							class="hover:bg-secondary hover:text-secondary-foreground data-[state=on]:bg-primary/20 data-[state=on]:text-primary flex-1 cursor-pointer rounded-full px-3 py-1.5 text-sm transition-colors"
						>
							{label}
						</ToggleGroup.Item>
					{/each}
				</ToggleGroup.Root>
			</div>

			<!-- Export Buttons -->
			<div class="mt-12 grid grid-cols-2 gap-3">
				<Button onclick={handleSingleExport} disabled={isExporting || !uploadedImage}>
					{#if isExporting}
						<SpinnerGapIcon size={20} class="animate-spin" /> Exporting...
					{:else}
						<DownloadSimpleIcon size={20} /> Export as {exportFormat}
					{/if}
				</Button>

				<!-- <Button onclick={handleAllFormatsExport} disabled={isExporting || !uploadedImage}>
					{#if isExporting}
						<SpinnerGapIcon size={20} class="animate-spin" /> Exporting All...
					{:else}
						<DownloadSimpleIcon size={20} /> Export All Formats
					{/if}
				</Button> -->
			</div>

			<a
				href="https://github.com/jellydeck/moocup"
				target="_blank"
				rel="noopener noreferrer"
				class="text-muted-foreground hover:text-foreground mt-3 inline-flex w-full items-center justify-center gap-2 py-2 text-sm transition-colors"
			>
				<GithubLogoIcon size={20} />
				Hey, You can also help us out here
			</a>
		</div>

		<!-- Support card col -->
		<div
			class={`border-primary/20 rounded-xl border-2 border-dashed p-5 ${!isMobile ? 'order-1' : 'order-2'} group`}
		>
			<HeartIcon
				size={20}
				weight="duotone"
				class="text-primary mb-4 transition-colors group-hover:animate-pulse"
			/>

			<div class="mb-4 space-y-1">
				<p class="text-foreground text-sm leading-relaxed">
					Hi, I'm
					<a
						href="https://jaydip.me"
						target="_blank"
						rel="noopener noreferrer"
						class="text-primary mx-1 inline-flex items-center gap-1 underline hover:no-underline"
					>
						Jaydip <ArrowSquareOutIcon size={12} />
					</a>
				</p>
				<p class="text-muted-foreground text-sm leading-relaxed">
					moocup is a simple offline tool.
				</p>
				<p class="text-muted-foreground text-sm leading-relaxed">
					focus on your craft, we'll take care of rest.
				</p>
				<p class="text-muted-foreground text-sm leading-relaxed">
					you can show your support by sponsoring my work!
				</p>
			</div>

			<div class="space-y-3">
				<a
					href="https://ko-fi.com/jaydipsanghani"
					target="_blank"
					rel="noopener noreferrer"
					class="bg-primary text-primary-foreground hover:bg-primary/90 flex h-12 w-full items-center justify-center gap-2 rounded-md font-medium shadow-md transition-colors"
				>
					<CoffeeIcon size={20} />
					Buy a coffee
				</a>

				<!-- UPI Dialog -->
				<Dialog.Root bind:open={isUpiDialogOpen}>
					<Dialog.Trigger
						class="border-primary/30 bg-background hover:bg-primary/5 hover:border-primary/50 flex h-12 w-full items-center justify-center rounded-md border font-medium transition-colors"
					>
						UPI (India)
					</Dialog.Trigger>
					<Dialog.Portal>
						<Dialog.Overlay
							class="data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-black/80"
						/>
						<Dialog.Content
							class="bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 fixed top-[50%] left-[50%] z-50 w-full max-w-xs translate-x-[-50%] translate-y-[-50%] rounded-xl border p-6 shadow-lg outline-none"
						>
							<Dialog.Title class="mb-4 text-center text-lg font-semibold">
								Thanks for contribution!
							</Dialog.Title>
							<div class="flex flex-col items-center gap-4 py-4">
								<div
									class="bg-muted border-muted-foreground/20 flex h-48 w-48 items-center justify-center rounded-xl border-2 border-dashed"
								>
									<img src={upiQR} class="size-full" alt="QR code for UPI payment" />
								</div>
								<p class="text-muted-foreground text-center text-sm">Scan with any UPI app</p>
							</div>
							<Dialog.Close
								class="absolute top-4 right-4 rounded-sm opacity-70 transition-opacity hover:opacity-100"
								aria-label="Close"
							>
								<XIcon size={16} />
							</Dialog.Close>
						</Dialog.Content>
					</Dialog.Portal>
				</Dialog.Root>
			</div>

			<!-- Social links -->
			<div class="mt-4 space-y-2">
				<h4 class="text-muted-foreground text-sm font-medium">
					Say Hi!
					<span class="ml-2 text-sm">I'm always up for quick chat :)</span>
				</h4>
				<div class="flex gap-2">
					<a
						href="https://bsky.app/profile/jellydeck.bsky.social"
						target="_blank"
						rel="noopener noreferrer"
						class="bg-secondary text-secondary-foreground hover:bg-secondary/80 flex h-9 flex-1 items-center justify-center gap-2 rounded-md text-sm transition-colors"
					>
						<!-- Bluesky has no Phosphor icon — inline SVG -->
						<svg
							width="16"
							height="16"
							viewBox="0 0 360 320"
							fill="currentColor"
							aria-hidden="true"
						>
							<path
								d="M180 142c-16-79-79-131-130-131C20 11 0 45 0 80c0 30 13 54 35 64C14 148 0 168 0 192c0 37 28 64 65 64 41 0 75-26 96-64 7-13 13-27 19-42 6 15 12 29 19 42 21 38 55 64 96 64 37 0 65-27 65-64 0-24-14-44-35-48 22-10 35-34 35-64 0-35-20-69-50-69-51 0-114 52-130 131z"
							/>
						</svg>
						Bluesky
					</a>
					<a
						href="https://x.com/JellyDeck"
						target="_blank"
						rel="noopener noreferrer"
						class="bg-secondary text-secondary-foreground hover:bg-secondary/80 flex h-9 flex-1 items-center justify-center gap-2 rounded-md text-sm transition-colors"
					>
						<XLogoIcon size={16} />
						Twitter
					</a>
				</div>
			</div>
		</div>
	</div>
{/snippet}

<!-- ─── Navbar ─────────────────────────────────────────────── -->
<div class="bg-background/80 sticky top-0 z-50 border-b border-border">
	<div class="flex h-16 items-center justify-between px-4 lg:mx-40">
		<!-- Logo -->
		<div class="flex items-center gap-4">
			<div class="flex items-center">
				<!-- <h1 class="text-primary text-xl font-bold">Moo</h1> -->
				<a href="https://ko-fi.com/jaydipsanghani" target="_blank" rel="noopener noreferrer">
					<CoffeeIcon
						size={24}
						class="text-primary hover:text-primary/80 cursor-pointer transition-transform hover:rotate-12"
					/>
				</a>
			</div>
			{#if !isMobile}
				<div class="text-muted-foreground flex items-center gap-2 text-sm">
					<span>crafted by</span>
					<a
						href="https://jaydip.me"
						target="_blank"
						rel="noopener noreferrer"
						class="text-primary text-sm underline hover:no-underline"
					>
						Jaydip
					</a>
				</div>
			{/if}
		</div>

		<!-- Actions -->
		<div class="flex items-center gap-2">
			<Button href="https://github.com/jellydeck/moocup" target="_blank" rel="noopener noreferrer">
				<GithubLogoIcon size={20} weight="bold" /> Send us a star!
			</Button>

			{#if isMobile}
				<!-- Mobile: Dialog -->
				<Dialog.Root bind:open={isDialogOpen}>
					<Dialog.Trigger
						disabled={!uploadedImage}
						class="bg-primary text-primary-foreground hover:bg-primary/90 flex h-10 w-10 items-center justify-center rounded-md transition-colors disabled:cursor-not-allowed disabled:opacity-50"
					>
						<DownloadSimpleIcon size={20} />
					</Dialog.Trigger>
					<Dialog.Portal>
						<Dialog.Overlay
							class="data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-black/80"
						/>
						<Dialog.Content
							class="bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 fixed top-[50%] left-[50%] z-50 flex h-[90vh] max-h-[90vh] w-[95vw] max-w-md translate-x-[-50%] translate-y-[-50%] flex-col rounded-xl border shadow-lg outline-none"
						>
							<div class="flex shrink-0 items-center justify-between border-b p-4">
								<Dialog.Title class="text-lg font-semibold">Export & Support</Dialog.Title>
								<Dialog.Close
									class="flex h-8 w-8 items-center justify-center rounded-md transition-colors hover:bg-accent"
								>
									<XIcon size={16} />
								</Dialog.Close>
							</div>
							<div class="flex-1 overflow-y-auto">
								<div class="px-4 pb-4">
									{@render exportOptions()}
								</div>
							</div>
						</Dialog.Content>
					</Dialog.Portal>
				</Dialog.Root>
			{:else}
				<!-- Desktop: Popover -->
				<Popover.Root>
					<Popover.Trigger>
						{#snippet child({ props })}
							<Button {...props} disabled={!uploadedImage}>
								Export
								<CaretDownIcon size={16} weight="bold" class="ms-2" />
							</Button>
						{/snippet}
					</Popover.Trigger>
					<Popover.Portal>
						<Popover.Content
							align="end"
							sideOffset={6}
							class="bg-background z-50 w-[900px] rounded-2xl border p-6 shadow-lg outline-none"
						>
							{@render exportOptions()}
						</Popover.Content>
					</Popover.Portal>
				</Popover.Root>
			{/if}
		</div>
	</div>
</div>
